# Generated by Django 2.1.4 on 2018-12-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaycounter',
            name='deadline',
            field=models.DateTimeField(default=''),
        ),
    ]
