# Generated by Django 2.1.5 on 2019-02-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('value', models.FloatField(blank=True)),
                ('sensor_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.SensorEntry')),
            ],
            options={
                'ordering': ('name', 'value', 'sensor_entry'),
            },
        ),
    ]
