# Generated by Django 2.1.5 on 2019-02-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='sensor_entry',
        ),
        migrations.AlterModelOptions(
            name='sensorentry',
            options={'ordering': ('name', 'type', 'value')},
        ),
        migrations.AddField(
            model_name='sensorentry',
            name='type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sensorentry',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
