# Generated by Django 2.1.5 on 2019-02-26 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20190226_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorentry',
            options={'ordering': ('name', 'type', 'value', 'created')},
        ),
        migrations.AddField(
            model_name='sensorentry',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 18, 42, 56, 237005)),
        ),
    ]
