# Generated by Django 2.1.5 on 2019-02-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20190226_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
