# Generated by Django 2.1.5 on 2019-02-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20190226_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
